//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGym.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public long Id { get; set; }
        public long SubscripationId { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal BalanceAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Paymentmode { get; set; }
        public string TransactionNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
