//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGym.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReg
    {
        public int Reg_Id { get; set; }
        public string Full_Name { get; set; }
        public string Mobile { get; set; }
        public string Photo { get; set; }
        public Nullable<decimal> Plans { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Address { get; set; }
    }
}
